version: '3.3'
services:
  db:
    networks:
      - dsflow
    build:
      context: ..
      dockerfile: ./db/Dockerfile
    image: dsflow/db
    networks:
      - dsflow
    hostname: db
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - $DSFLOW_WORKSPACE/tmp/pgdata:/var/lib/postgresql/data/pgdata
