version: '3.3'
services:
  job-generator:
    networks:
      - dsflow
    build:
      context: ../..
      dockerfile: ./docker/dsflow-job-generator/Dockerfile
    image: dsflow/job-generator
    environment:
      DSFLOW_DATASTORE_ROOT: /data
      DSFLOW_JOBS_ROOT: /jobs
      DSFLOW_ROOT: /usr/src/app
    # ports:
    #   - 4040:4040
    #   - 8998:8998
    #   - 8888:8888
    expose:
      - 8998
    volumes:
      - $DSFLOW_WORKSPACE/datastore:/data
      - $DSFLOW_WORKSPACE/adhoc:/adhoc
      - $DSFLOW_WORKSPACE/jobs:/jobs
      - $DSFLOW_ROOT/python_scripts:/usr/src/app/python_scripts
      - $DSFLOW_ROOT/templates:/usr/src/app/templates

networks:
  dsflow:
    external: true
